// Generated by CoffeeScript 1.6.3
/*global define*/


(function() {
  define(['game', 'jquery'], function(Game, $) {
    'use strict';
    var Application;
    Application = function() {
      this.game = new Game();
      $('.new-game').on('click', this.game.clearGame);
      $('.clear-score').on('click', this.game.clearScore);
    };
    return Application;
  });

}).call(this);
